ollionorg/datapipes-airbyte

airbyte-integrations/connectors/source-oracle/build.gradle

test:Update build.gradle

---

airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/MssqlSource.java

fix: DPA-1803 MSSQL failing for custom SQL

---

airbyte-integrations/connectors/source-salesforce/metadata.yaml
airbyte-integrations/connectors/source-salesforce/source_salesforce/source.py
airbyte-integrations/connectors/source-salesforce/source_salesforce/streams.py
airbyte-integrations/connectors/source-salesforce/unit_tests/discovery_test.py

feat: DPA-1988 End Date for Salesforce Stream

---

airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/source/jdbc/AbstractJdbcSource.java
airbyte-integrations/connectors/source-oracle/metadata.yaml

feat: ✨ Discover for custom SQL using jdbc connection

---

DP-CHANGELOG.md
airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/source/jdbc/AbstractJdbcSource.java
airbyte-integrations/connectors/source-mssql/metadata.yaml
airbyte-integrations/connectors/source-mysql/metadata.yaml
airbyte-integrations/connectors/source-oracle/metadata.yaml
airbyte-integrations/connectors/source-postgres/metadata.yaml

fix: Discover for custom SQL using jdbc connection

---

airbyte-integrations/connectors/source-brightspace/metadata.yaml
airbyte-integrations/connectors/source-brightspace/source_brightspace/spec.yaml

fix: updated spec file of brightspace and version

---

airbyte-integrations/connectors/source-file/metadata.yaml
airbyte-integrations/connectors/source-file/source_file/client.py

fix: DPA-2361 Source File Data Type issue

---

airbyte-integrations/connectors/source-brightspace/metadata.yaml
airbyte-integrations/connectors/source-brightspace/source_brightspace/streams.py

fix: bds stream fix

---

airbyte-integrations/connectors/source-brightspace/metadata.yaml
airbyte-integrations/connectors/source-brightspace/source_brightspace/spec.yaml
airbyte-integrations/connectors/source-brightspace/source_brightspace/streams.py

fix: DPA-2363 Brightspace update connector configuration

---

airbyte-integrations/connectors/source-brightspace/source_brightspace/streams.py

fix: DPA-2397 Error while adding bds connector

---

airbyte-integrations/connectors/source-mssql/metadata.yaml
airbyte-integrations/connectors/source-mssql/src/main/java/io/airbyte/integrations/source/mssql/MssqlSourceOperations.java

fix: DPA-2627 MSSQL Datetime datatype issue

---

airbyte-integrations/connectors/source-brightspace/metadata.yaml
airbyte-integrations/connectors/source-brightspace/source_brightspace/spec.yaml
airbyte-integrations/connectors/source-brightspace/source_brightspace/streams.py

fix: DPA-2752 Make roles option field for ADS

---

airbyte-integrations/connectors/source-file/source_file/client.py

fix: add stream name for source-file

---

airbyte-integrations/connectors/source-file/CHANGELOG.md
airbyte-integrations/connectors/source-file/metadata.yaml

fix: update source-file version

---

airbyte-integrations/connectors/source-file/Dockerfile
airbyte-integrations/connectors/source-file/metadata.yaml

fix: gnupg issue

---

airbyte-cdk/java/airbyte-cdk/core/src/main/java/io/airbyte/cdk/db/jdbc/AbstractJdbcCompatibleSourceOperations.java
airbyte-cdk/java/airbyte-cdk/core/src/main/java/io/airbyte/cdk/db/jdbc/StreamingJdbcDatabase.java
airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/source/relationaldb/RelationalDbQueryUtils.java
airbyte-integrations/connectors/source-oracle/metadata.yaml

fix: Add debug in Oracle image

---

airbyte-integrations/connectors/source-file/Dockerfile
airbyte-integrations/connectors/source-file/setup.py

Source file gnupg

---

airbyte-integrations/connectors/source-brightspace/metadata.yaml
airbyte-integrations/connectors/source-brightspace/source_brightspace/streams.py

fix: add big int datatype in brightspace

---

airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/source/relationaldb/AbstractDbSource.java
airbyte-integrations/connectors/source-oracle/metadata.yaml

fix: Removed error when cursorType is not found

---

airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/source/jdbc/AbstractJdbcSource.java
airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/source/relationaldb/AbstractDbSource.java
airbyte-integrations/connectors/source-oracle/metadata.yaml

fix: Added a fix for derived columns

---

airbyte-cdk/java/airbyte-cdk/core/src/main/java/io/airbyte/cdk/db/IncrementalUtils.java
airbyte-cdk/java/airbyte-cdk/db-sources/src/main/java/io/airbyte/cdk/integrations/source/relationaldb/AbstractDbSource.java
airbyte-integrations/connectors/source-oracle/metadata.yaml

fix!: for derived column if datetimestamp

---

airbyte-integrations/connectors/source-mysql/metadata.yaml
airbyte-integrations/connectors/source-mysql/src/main/java/io/airbyte/integrations/source/mysql/MySqlSource.java

fix: Derived column query fix for mySQL

---

airbyte-cdk/java/airbyte-cdk/core/src/main/java/io/airbyte/cdk/db/jdbc/streaming/AdaptiveStreamingQueryConfig.java
airbyte-integrations/connectors/source-oracle/metadata.yaml

fix: Oracle fetch size

---

airbyte-cdk/java/airbyte-cdk/core/src/main/java/io/airbyte/cdk/db/jdbc/streaming/AdaptiveStreamingQueryConfig.java
airbyte-integrations/connectors/source-oracle/metadata.yaml

fix: Oracle custom fetch size
